apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
